### PR TITLE
use `ok` in `normalize`

### LINKED ISSUE #222: Fix `normalize` to ignore bad data.
Right now, `normalize` just uses the `nanmedian` of all the fluxes, regardless of quantity. 
- Fix that so it is aware of which data points are `ok` or not.
- Give a warning if the normalization factor is negative.

### PR DESCRIPTION
**Pull request by zkbt**
- Add `get_ok_data` as (possibly pointless) wrapper to get flux with bad data replaced with `nan`.
- Fix `normalize` to now use `ok`. 
- Add warning to `normalize` if any of the normalization factors are negative, with suggestion for fix. 
- Add more tests for `normalize`.
Closes #222 . Passes tests.

### CODE REVIEW

**Comment by zkbt** [comment]
@catrionamurray , this should now at least ignore values that are not `ok` in the normalization. It will still happily normalize by a negative number and therefore produce negative uncertainties, but at least it warns you about it now. I think for the vast majority of applications you could probably consider negative median flux as making a wavelength effectively useless.

**Comment by catrionamurray** [comment]
This is great, thank you! I think that maybe a statements in the __init__ file is missing? Should there be `from .fluxlike import *` in the /get/__init__.py?

**Comment by zkbt** [comment]
Oh, yeah, I guess so. I think it works for me without it because the only place it's needed is as a direct import into the `Rainbow` class definition...

https://github.com/zkbt/chromatic/blob/567e1319414d0b37935b2ca061efe78d67fcad6e/chromatic/rainbows/rainbow.py#L1018

...but it's possible that including in the `get/__init__.py` helps for some other versions of Python?

**Comment by zkbt** [comment]
(Just updated this directly in the `develop` branch).

**Pull request merged**
