### PR TITLE
Adding stellar spectrum + batman transits to simulated.py

### PR DESCRIPTION
**Pull request by madisontbrady**
Additions:

-in simulated.py:
Ability to input a stellar flux star_flux into SimulatedRainbow class (assumed static with time).  
function SimulatedRainbow.inject_transit(), which takes in a dictionary of planetary parameters and an array of R_planet/R_star with wavelength (or just a float if it's constant with wavelength).  This modifies the object in-place and can be called multiple times with different planetary parameters if desired.  (potential future work: make it return a new Rainbow() with the planet added)

-batman import to imports.py
-some new tests of these functionality in test_simulated_rainbow.py

### CODE REVIEW

**Comment by zkbt** [comment]
Ooh, this is so exciting! I'll take a look at this now!

**Comment by zkbt** [comment]
@madisontbrady , I love this! It seems to work for me, after I made one small change. Your version was relying on the `.time` always being in units of days; I made sure that the units will definitely be fed into batman as days.

I did a few other small things:

- I made a couple of tiny nudges to the tests to split them up to test closer to one thing at a time.
- I changed it so `batman.TransitModel` would initalize the transit model only once. The way Laura has that set up, there's a lot of overhead in initializing the model, but it's a lot fast to just change its parameters and produce a new light curve.
- I added `batman-package` as a dependency.

If you pull down my changes, do they still work for you?

**Comment by zkbt** [comment]
This brought up a few other design questions for me, but it's so good and useful we should merge it in soon and then fiddle with things from there!

**Comment by zkbt** [comment]
image

I like this so much!

**Comment by madisontbrady** [comment]
The changes don't cause any problems with me. I updated the function description a bit to more accurately reflect what units things should be in.  Do you think it would be fruitful to make this output another Rainbow() object instead of changing the Rainbow() in place?  It would be more like lightkurve if we did that.

**Comment by madisontbrady** [comment]
This also doesn't support wavelength-dependent limb darkening, which is a possible future edit.

**Comment by zkbt** [comment]
I agree that having this return a separate `Rainbow` object has a lot of nice benefits to it. However, let's merge this in, and then think later about that restructuring. This is so awesome! Great work, @madisontbrady !

**Pull request merged**
