### PR TITLE
add plot_quantities function

### LINKED ISSUE #47: Add a function to plot all `timelike` quantities.
Many datasets will have multiple arrays associate with them that are "time-like", in the sense that there's one number for each time point. The most obvious time-like quantity is `time` itself, but there could be many others (average centroid shifts, detector temperatures, etc..). This is effectively trying to plot every array in the `rainbow.timelike` dictionary.

It'd be great to have a function that just makes a quick plot of all these quantities, in its own subplot. They should have a shared x-axis, so we can see things line up across all the panels. This might look something like `def plot_timelike_quantities(rainbow, quantities=None):`, where `quantities = None` would mean to just plot everything and `quantities = ['time', 'centroid', 'temperature']` would plot just a subset of quantities. 

To start developing this, the simplest approach is probably to just write a function in a notebook. Test it on some Rainbow object, and then once it behaves how you like, we can drop it into the code for the `chromatic` package. (I can post more specific instructions on how to do that below.) 

So, to get started, you might open a notebook and run  

```
from chromatic import *
rainbow = SimulatedRainbow().inject_transit()

def ...
```

and then start drafting your function.

### LINKED ISSUE #48: Add a function to plot all `wavelike` quantities.
Many datasets will have multiple arrays associate with them that are "wave-like", in the sense that there's one number for each wavelength. The most obvious wave-like quantity is `wavelength` itself, but there could be many others (average stellar spectrum, mean saturation, mean background level). This is effectively trying to plot every array in the `rainbow.wavelike` dictionary.

It'd be great to have a function that just makes a quick plot of all these quantities, in its own subplot. They should have a shared x-axis, so we can see things line up across all the panels. This might look something like `def plot_wavelike_quantities(rainbow, quantities=None):`, where `quantities = None` would mean to just plot everything and `quantities = ['wave', 'stellar_spectrum']` would plot just a subset of quantities. 

To start developing this, the simplest approach is probably to just write a function in a notebook. Test it on some Rainbow object, and then once it behaves how you like, we can drop it into the code for the `chromatic` package. (I can post more specific instructions on how to do that below.) 

So, to get started, you might open a notebook and run  

```
from chromatic import *
rainbow = SimulatedRainbow().inject_transit()

def ...
```

and then start drafting your function.

### PR DESCRIPTION
**Pull request by lcmayor**
This PR changes the following:
- Adds function `plot_quantities` to close #47 and close #48

### CODE REVIEW

**Review by zkbt — APPROVED** [review]
This is awesome! Thanks, @lcmayor ! 

I expanded the test a little bit to better cover:
- both time and wavelength
- rainbows that actually contain multiple quantities
- different choices for `x_axis`

I also made a few tiny changes to the default appearance:
- To help take advantage of the shared x-axis for everything, I changed the default `maxcol` to 1, so they all line up on top of each other.
- I made the default panel size a little wider.

**Comment by zkbt** [comment]
Thanks for more lovely code, @lcmayor ! 

In trying to follow your advice of setting up a permanent `develop` branch that features get merged into before being released to `main`, I've run into a question. I can see how I'd do that merging on my own computer, but if I want to use the friendly green "Merge Pull Request" button on `github`, it sends it automatically to `main`. Do you know if that's a setting I can change?

**Comment by lcmayor** [comment]
When the PR is made (on GitHub) there should be an option to change that. I think there's a dropdown to change the "compare to" to develop and then when you click to merge the PR it'll go to develop instead.

You can choose to set the develop branch as the default branch, which'll show up when you navigate to the repo on Github. The danger there is that when you git clone it, you'll get the develop branch.

**Comment by zkbt** [comment]
Awesome, thanks! I just switched over to `develop` as the "default" branch in github. I *think* that's OK in that the folks who will be cloning the repository probably want to develop on it, and folks who don't want to mess with it at all will probably just install via `pip` (which I'll keep synced to `main`). Fingers crossed?

**Pull request merged**
