### PR TITLE
MCR develop

### LINKED ISSUE #73: Add reader for NIRISS/SOSS x1d outputs (specifically ATOCA)
Currently the existing x1d reading interface does not play well with the outputs of the ATOCA extraction algorithm for NIRISS/SOSS. Need to implement a new reader to handle this.
Other pipelines (e.g., eureka!) may output different formats - functionality to handle these can be added as they become more mature.

### PR DESCRIPTION
**Pull request by radicamc**
Fixes #73. ATOCA x1d outputs can now be read into a Rainbow object by specifying format='atoca' at initialization.

### CODE REVIEW

**Comment by zkbt** [comment]
Awesome! I'll take a look soon, probably sometime early next week?

**Comment by radicamc** [comment]
> Awesome! I'll take a look soon, probably sometime early next week?

Oops! Just saw this after I realized it could be merged without review!

**Comment by zkbt** [comment]
This looks good by me. Could you please send an example file I could try it out on? I've avoided including explicit automatic tests for every reader because for some I don't have easy access to tiny files that would be reasonable to distribute with the code, but I'd still love to see how this works on a real file.

**Comment by radicamc** [comment]
No problem, just sent one over slack.

**Pull request merged**
