### PR TITLE
Add ability to say `r.time = ...` (and other quantities too).

### PR DESCRIPTION
**Pull request by zkbt**
This Pull Request changes how the data are retrieved from and set in the core dictionaries. The key changes are as follows:
- Before this, you couldn't say something like `r.time = ...`, because the time "property" only retrieved data from the `r.timelike['time']` and could not change values in that dictionary. Now, saying `r.time = ...` will work and will store whatever quantities get assigned into the `.timelike['time']` array. The affected properties include `time`, `wavelength`, `flux`, `uncertainty`, and `ok`.
- Before this, you had to explicitly add auxiliary arrays to the appropriate dictionaries. Let's say you had an array of detector temperature as a function of time; the only way to store it with other timelike quantities would be to say `r.timelike['detector_temperature'] = ...`. Now, you can say `r.detector_temperature = ...`, and chromatic will try (usually pretty accurately!) to guess into which core dictionary the array should be stored, based on its shape.

### CODE REVIEW

**Comment by zkbt** [comment]
This should address #86 . 

@Pat-Wachiraphan , could you please try out this change and let me know if it works how you would expect? To do so, I think you should be able to do `git fetch; git checkout fix-properties` to switch into the branch with these changes, and then try that version of the code. 

Once you've tested it, please reply here letting me know whether or not it works. Thanks!

**Comment by Pat-Wachiraphan** [comment]
@zkbt  I've tested this ability, and it works great! I love that you add the second key change!

However, I have a suggestion here,

- Can we bring up the warning when users try to assign the list/array that does not match the previous property's shape? it doesn't allow the change in that case, but it doesn't prompt any error/warning either.

**Comment by zkbt** [comment]
Ooh, that's a great suggestion, Pat! To be clear, you mean like changing the time array from something that contains `N` elements to something that contains `N-1` elements? When that happens, give a warning or a friendlier error message?

**Comment by zkbt** [comment]
Actually, the easiest might be just send me a code snippet of what you were trying to do?

**Comment by Pat-Wachiraphan** [comment]
will do.

______________________________
Pat Wachiraphan (he, him, his)
Graduate Student,
Dept. of Astrophysical & Planetary Sciences
University of Colorado Boulder
***@***.***

**Comment by Pat-Wachiraphan** [comment]
> that contains `N-1` elements? When that happens, give a warning or a friendli

that's right! I think some friendly warning that chromatic didn't change anything from the last command, something like that would be great! 

Here is some code I tried,

Code:
```from chromatic import * 
import matplotlib.pyplot as plt
import astropy.units as u
import numpy as np
phase = np.loadtxt("phase.txt")
r = Rainbow("data/*_x1dints.fits")
print (r.time,len(r.time))
b.time = b.time[:-2]
print (r.time,len(r.time))
```

it didn't show any error message now, instead it just pass the command!

Output:
```
[0.00000000e+00 5.52222222e-04 1.10444444e-03 ... 1.01940222e+00
 1.01995444e+00 1.02050667e+00] d 1849
[0.00000000e+00 5.52222222e-04 1.10444444e-03 ... 1.01940222e+00
 1.01995444e+00 1.02050667e+00] d 1849
```

**Comment by zkbt** [comment]
OK, I think it should automatically warn you now if the shapes are inconsistent? When you get a chance, can you please give it a try and confirm it does what you'd like?

(Please pardon the weird night-time commit! I'm coding while the baby sleeps!)

**Comment by Pat-Wachiraphan** [comment]
All good! thanks!

**Comment by zkbt** [comment]
Awesome, thanks!

**Pull request merged**
